version: "3.9"

services:

  solr:
    container_name: ossearch-solr-latest
    image: solr:latest
    restart: always
    environment:
      - SOLR_OPTS=-XX:CompileCommand=exclude,com.github.benmanes.caffeine.cache.BoundedLocalCache::put -Dsolr.disable.allowUrls=true
    ports:
      - 8983:8983
    networks:
      - ossearch
#    command:
#      - -c
#      - solr-precreate
#      - external-v1_FULL
    volumes:
      - ./data/mycores_solr_latest:/var/solr #sudo chown 8983:8983

  db:
    container_name: ossearch-mysql-lower
    image: mysql:8
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 26677
        hard: 46677
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: si_search_db_dmz
      MYSQL_USER: ossearch
      MYSQL_PASSWORD: ossearch
    command: --lower_case_table_names=1 --innodb-buffer-pool-size=200M
    user: mysql
    ports:
      - 3309:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - ossearch

# container networks
networks:
  ossearch: